# Default values for ipfs-testbed.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

toxiproxy:
  image:
    repository: shopify/toxiproxy
    tag: latest
    pullPolicy: IfNotPresent
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 20
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 20
  config:
    - name: "ipfs_swarm"
      listen: "0.0.0.0:8002"
      upstream: "0.0.0.0:4002"

ipfs:
  image:
    repository: registry.gitlab.com/jgantunes/js-ipfs
    tag: latest
    pullPolicy: IfNotPresent
  env:
    - name: DEBUG
      value: "libp2p*,jsipfs*"
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 20
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 20
  config:
    Discovery:
      MDNS:
        Enabled: false
      webRTCStar:
        Enabled: true
    Bootstrap: []

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  swarm:
    port: 8002
  toxiproxyAPI:
    port: 8474
  ipfsAPI:
    port: 5002

nodeSelector: {}

tolerations: []

affinity: {}
